# Generated by Django 2.2.6 on 2019-10-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20191026_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='Teacher_image'),
        ),
    ]
