# Generated by Django 2.2.6 on 2019-11-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20191028_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='famous', max_length=10, verbose_name='tag'),
        ),
    ]
