# Generated by Django 2.2.6 on 2019-10-19 21:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('desc', models.CharField(max_length=300, verbose_name='Description')),
                ('detail', models.TextField(verbose_name='Detail')),
                ('degree', models.CharField(choices=[('1', 'beginner'), ('2', 'intermediate'), ('3', 'advance')], max_length=2)),
                ('learn_times', models.IntegerField(default=0, verbose_name='learn length(minute)')),
                ('students', models.IntegerField(default=0, verbose_name='StudentNumber')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='Fav_nums')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='image')),
                ('click_nums', models.IntegerField(default=0, verbose_name='ClickNum')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Addtime')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='LessonName')),
                ('learn_times', models.IntegerField(default=0, verbose_name='LearnTime')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Addtime')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='VideoName')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Addtime')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='File')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Addtime')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'CourseResource',
                'verbose_name_plural': 'CourseResources',
            },
        ),
    ]
