# Generated by Django 2.2.6 on 2019-10-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20191027_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='backend', max_length=20, verbose_name='CourseCategory'),
        ),
    ]
