# Generated by Django 2.2.6 on 2019-10-19 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='Banner')),
                ('url', models.URLField(verbose_name='URL')),
                ('index', models.IntegerField(default=100, verbose_name='Index')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Addtime')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='VerifyCode')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('sen_type', models.CharField(choices=[('r', 'register'), ('f', 'forgot')], max_length=30, verbose_name='SendType')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'VerifyCode',
                'verbose_name_plural': 'VerifyCodes',
            },
        ),
    ]
