# Generated by Django 2.2.6 on 2019-10-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191019_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverifyrecord',
            old_name='sen_type',
            new_name='send_type',
        ),
    ]
